name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        run: deno fmt --check
        
      - name: Lint
        run: deno lint

      - name: Test
        run: deno task test

      - name: Publish package
        run: npx jsr publish